module.exports = {
  OTP: '_OTP_',
  LATE_LOGIN: '_LATE_LOGIN_',
  ACCIDENT_CATEGORY: '_ACCIDENT_CATEGORY_',
  MAINTENANCE_CATEGORY: '_MAINTENANCE_CATEGORY_',
  LEAVETYPE: ['AL', 'LL', 'SL', 'EL' ],
  BOOKINGTYPE: ['scheduled', 'onDemand', 'departmentToken'],
  NOTIFICATION:'_NOTIFICATION_',
  HANDOVER_TAKEOVER: '_HANDOVER_TAKEOVER_',
  COMMS_AUTH_TOKEN: '_COMMS_AUTH_TOKEN_',
  RATE_LIMIT : '_RATE_LIMIT_'
};