apiVersion: v1
data:
  AWS_SECRET_ACCESS_KEY: xxxxxxxxxxxxxxxxxxxxxxx
  BUDDY_BFF_KEY: xxxxxxxxxxxxxxxxxxxxxxx
  COMM_AUTH_PASSWORD: xxxxxxxxxxxxxxxxxxxxxxx
  JWT_SECRET: xxxxxxxxxxxxxxxxxxxxxxx
  MGW_DRIVER_KEY: xxxxxxxxxxxxxxxxxxxxxxx
  MGW_MICROSRV_KEY: xxxxxxxxxxxxxxxxxxxxxxx
  MGW_SMS_KEY: xxxxxxxxxxxxxxxxxxxxxxx
  MGW_VEHICLE_KEY: xxxxxxxxxxxxxxxxxxxxxxx
  MONGO_PASS: xxxxxxxxxxxxxxxxxxxxxxx
  MSAL_CLIENT_SECRET: xxxxxxxxxxxxxxxxxxxxxxx+xxxxxxxxxxxxxxxxxxxxxxx==
  REDIS_PASSWORD: "xxxxxxxxxxxxxxxxxxxxxxx"
  MSAL_SSO_CLIENT_SECRET: xxxxxxxxxxxxxxxxxxxxxxx+xxxxxxxxxxxxxxxxxxxxxxx==
kind: Secret
metadata:
  name: xxxxxxxxxxxxxxxxxxxxxxx
  namespace: default-dev
type: Opaque